name: CI/CD Pipeline
on:
  push:
    branches:
      - 'master'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - 
        name: checkout package
        uses: actions/checkout@v1
      - 
        name: 'Install Node'
        uses: actions/setup-node@v1
      - 
        name: Install mocha
        run: npm install -g mocha
      -
        name: Install dependencies
        run: npm install --save mocha chai
             npm install --save request
             npm install --save should
      - 
        name: "Run Test"
        run: mocha test/server.js

  build:
    needs: test
    runs-on: ubuntu-latest


    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker_ebusiness:latest


  deploy:
    needs: build
    runs-on: ubuntu-latest  
    steps:
        - 
          name: deploy Website
          uses: appleboy/ssh-action@master
          with:
            host: ${{secrets.DIGITALOCEAN_SSH_IP}}
            username: ${{secrets.DIGITALOCEAN_SSH_USER}}
            password: ${{secrets.DIGITALOCEAN_SSH_PASSWORD}}
            port: ${{secrets.DIGITALOCEAN_SSH_PORT}}

            script: |
                docker pull ${{secrets.DIGITALOCEAN_SSH_USER}}/docker_ebusiness
                docker stop test
                docker rm test
                docker run -it -d -p 80:80 --name test ${{secrets.DIGITALOCEAN_SSH_USER}}/docker_ebusiness

  inform_contributors:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: mail.vhs.cloud
          # Required mail server port:
          server_port: 587
          # Optional (recommended): mail server username:
          username: ${{secrets.EMAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.EMAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: ${{secrets.ADDRESS_DILEXX}}; ${{secrets.EMAIL_USERNAME}}; ${{secrets.ADDRESS_YONDONO}}
          # Required sender full name (address can be skipped):
          from: Grandmaster Fulk # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: false
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!