name: upload
on:
  push:
    branches:
      - 'master'


jobs:
  deploy:
    runs-on: ubuntu-latest  
    steps:
        - 
          name: deploy Website
          uses: appleboy/ssh-action@master
          with:
            host: ${{secrets.SSH_HOST}}
            username: ${{secrets.SSH_USERNAME}}
            password: ${{secrets.SSH_PASSWORD}}
            port: ${{secrets.SSH_PORT}}

            script: |
                mkdir repo
                cd repo
                git clone https://github.com/JohnGoku/eBusiness.git
                cd eBusiness
                git pull
                cp -f *.html *.pdf /var/www/html
                echo "finished deployment"
